name: fetch daily wordle answer
# a workflow file that fetches the daily wordle answer from the new york times. it's an unofficial api so it may be deprecated in the future.
on:
  schedule:
    # runs every mondayat 6:25am UTC --> 12:25am cst --> 1:25am est
    - cron: '25 6 * * 1'
  workflow_dispatch: {}   # allows manual trigger from github actions tab

permissions:
  contents: write

jobs:
  update-answer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: fetch a week's worth of nyt wordle answers (assuming they are always a week out)
        run: python3 .github/scripts/fetch-weekly-wordle-answers.py

      - name: Commit and push if the answers changed
        run: |
          DATE=$(date -u +%Y-%m-%d)
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pichordle/week-answers.json
          git diff --staged --quiet || git commit -m "updated the wordle answers for the week of ${DATE}"
          git push
